# This is a basic workflow to help you deploy theme changes

name: Build and deploy to Github artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install

      - name: Build artifacts for production
        run: npm run prod

      - uses: actions/upload-artifact@v2
        with:
          name: site-theme
          path: ${{ github.workspace }}/dist/**/*

      - name: Updated theme path
        env:
          URL: ${{ secrets.URL }}
          AEM_USER: ${{ secrets.AEM_USER }}
          AEM_PASS: ${{ secrets.AEM_PASS }}
          SITE: ${{ secrets.SITE }}
        run: echo "TODO - update theme path"
